[package]
name = "degree-explorer"
version = "0.1.0"
authors = ["Voovs Selin <Voovs.13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = "0.18"
wasm-bindgen = "0.2"
